name: flutter_melos_starter_workspace
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  melos: ^7.4.0

workspace:
  - apps/app
  - packages/core
  - packages/app_config
  - packages/auth
  - packages/posts
