name: posts
description: Hacker News posts feature (list + details) using clean architecture.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  url_launcher: ^6.3.2
  go_router: ^17.1.0

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  # Networking
  dio: ^5.9.1

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Codegen (Injectable)
  build_runner: ^2.11.1
  injectable_generator: ^2.12.0
