name: core
description: Shared core utilities for Flutter apps (result, errors, logging, networking).
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.1
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
